management:
    info:
        git:
            mode: full
server:
#    servlet:
#        contextPath: /api/v1
    port: 8080
spring:
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://${app.db.host}:3306/${app.db.name}
        username: ${app.db.username}
        password: ${app.db.password}
    jpa:
        hibernate.ddl-auto: update
        generate-ddl: true
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    jackson:
        date-format: com.amdexa.misc.arm.RFC3339DateFormat
        serialization:
            WRITE_DATES_AS_TIMESTAMPS: false
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: ${app.auth.issuer_uri}
springfox:
    documentation:
        swagger:
            v2:
                path: /api-docs

auth0:
    audience: ${app.auth.audience}
    client_id: ${app.auth.client_id}
    client_secret: ${app.auth.client_secret}

logging:
    level:
        org:
            springframework:
                security: DEBUG