management:
    info:
        git:
            mode: full
server:
    contextPath: /v1
    port: 8080
spring:
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://${app.db.host}:3306/${app.db.name}
        username: ${app.db.username}
        password: ${app.db.password}
    jpa:
        hibernate.ddl-auto: update
        generate-ddl: true
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    jackson:
        date-format: com.amdexa.misc.arm.RFC3339DateFormat
        serialization:
            WRITE_DATES_AS_TIMESTAMPS: false
springfox:
    documentation:
        swagger:
            v2:
                path: /api-docs
